language: python
sudo: false

notifications:
    email: false

python:
  - "3.7"

# only run travis on the master branch
branches:
    only:
        - master

# install dependencies listed in requirements
install: 
  - pip install -r requirements.txt
  - pip install .

# run tests
script:
  - pytest -v tests/numba_parallel_diagnostics.py

after_success:
  - codecov
