language: python
sudo: false

notifications:
    email: false

python:
  - "3.8"

# only run travis on the master branch
branches:
    only:
        - master

# install dependencies listed in requirements
install: 
  - pip install -r requirements.txt
  - pip install .

# run tests
script:
  - flake8
  - black --check .
  - python setup.py check --restructuredtext
  - pytest --cov-report=xml --cov=scvi -v tests/numba_parallel_diagnostics.py

after_success:
  - codecov
  - pip list
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Python -r coverage.xml    